-- ===========================================================================
-- 003 — Dicionario de categorias (categoria -> analise e grupo do DRE)
--
-- Aposenta o dados_log.parquet: um arquivo de 14 MB, exportacao antiga da
-- planilha "Log", cuja UNICA funcao era responder "esta categoria entra no DRE
-- ou no fluxo de caixa, e em que grupo?". Sao 110 respostas; nao
-- precisavam de 14 MB nem de um arquivo que o Render apaga a cada reinicio.
--
-- Isto e uma REDE DE SEGURANCA, nao a regra principal: quando o proprio OMIE
-- informa a conta do DRE da categoria, e ele quem manda. Esta tabela responde
-- pelas categorias antigas que o OMIE nao classifica.
--
-- Categoria que aparecer no OMIE e nao estiver aqui cai numa regra automatica
-- (palavras como "aporte", "emprestimo", "transferencia" indicam fluxo de
-- caixa; o resto vai para o DRE). Para corrigir uma classificacao, edite a
-- linha correspondente numa migracao nova — nunca com UPDATE solto.
-- ===========================================================================
INSERT INTO painel.categoria_de_para (categoria, analise, grupo, origem) VALUES
    ('13º Salário', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Agregados Areia Brita Arisco', 'DRE', 'Materiais Aplicados', 'log'),
    ('Aluguéis e Condomínios', 'DRE', 'Despesas Administrativas', 'log'),
    ('Aplicações Financeiras', 'Fluxo de Caixa', 'Saídas Financeiras', 'log'),
    ('Aportes BWS', 'Fluxo de Caixa', 'Saídas Financeiras', 'log'),
    ('Aportes Parceiros', 'Fluxo de Caixa', 'Entradas Financeiras', 'log'),
    ('Aquisição de Veículos Máquinas e Equipamentos', 'DRE', 'Compra de Ativos', 'log'),
    ('Argamassas', 'DRE', 'Materiais Aplicados', 'log'),
    ('Armadura', 'DRE', 'Materiais Aplicados', 'log'),
    ('Bancadas de Granito', 'DRE', 'Materiais Aplicados', 'log'),
    ('COFINS', 'DRE', 'Despesas Tributárias', 'log'),
    ('COFINS Retido', 'DRE', 'Receitas', 'log'),
    ('CPRB', 'DRE', 'Despesas Tributárias', 'log'),
    ('CSLL', 'DRE', 'Despesas Tributárias', 'log'),
    ('CSLL Retido', 'DRE', 'Receitas', 'log'),
    ('Cartórios Crea Taxas', 'DRE', 'Despesas Administrativas', 'log'),
    ('Cesta Básica', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Cimento e Concreto Usinado', 'DRE', 'Materiais Aplicados', 'log'),
    ('Combustíveis', 'DRE', 'Despesas Administrativas', 'log'),
    ('Conservação e Manutenção Predial', 'DRE', 'Compra de Ativos', 'log'),
    ('Consultoria Contabilidade Jurídica', 'DRE', 'Despesas Administrativas', 'log'),
    ('Cursos e Treinamentos', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Cópias Reproduções e Impressões', 'DRE', 'Despesas Administrativas', 'log'),
    ('Despesas com Alimentação', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Despesas com Transporte', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Despesas com Viagens e Estadia', 'DRE', 'Despesas Administrativas', 'log'),
    ('Devolução de Aportes', 'Fluxo de Caixa', 'Saídas Financeiras', 'log'),
    ('Devolução de Mercadoria inativa', 'DRE', 'Receitas', 'log'),
    ('Dividendos Recebidos', 'DRE', 'Entradas Financeiras', 'log'),
    ('EPI Equipamento de Proteção Individual', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Elementos de Vedação Tijolo Blocos e Paredes PVC', 'DRE', 'Materiais Aplicados', 'log'),
    ('Empréstimos Pgt. do Principal', 'Fluxo de Caixa', 'Saídas Financeiras', 'log'),
    ('Empréstimos para Capital de Giro', 'Fluxo de Caixa', 'Entradas Financeiras', 'log'),
    ('Encargos Sociais FGTS', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Encargos Sociais INSS', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Entrada de Transferência', 'TRF', 'Transferência', 'log'),
    ('Equipamentos de Informática', 'DRE', 'Compra de Ativos', 'log'),
    ('Esquadrias de Alumínio Metal e Madeira', 'DRE', 'Materiais Aplicados', 'log'),
    ('Estorno de Despesas', 'DRE', 'Receitas', 'log'),
    ('Estrutura Metálica', 'DRE', 'Materiais Aplicados', 'log'),
    ('Exames Médicos', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Ferramentas', 'DRE', 'Materiais Aplicados', 'log'),
    ('Fretes e Postagens', 'DRE', 'Despesas com Terceiros', 'log'),
    ('Fundo Fixo', 'DRE', 'Materiais Aplicados', 'log'),
    ('Férias', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Gratificações e Extras', 'DRE', 'Despesas com Pessoal', 'log'),
    ('ICMS Diferencial de Alíquota', 'DRE', 'Materiais Aplicados', 'log'),
    ('INSS Retido', 'DRE', 'Receitas', 'log'),
    ('IR Retido', 'DRE', 'Receitas', 'log'),
    ('IRPJ', 'DRE', 'Despesas Tributárias', 'log'),
    ('ISS', 'DRE', 'Despesas Tributárias', 'log'),
    ('ISS Retido', 'DRE', 'Receitas', 'log'),
    ('Impermeabilizantes Aditivos e Colas', 'DRE', 'Materiais Aplicados', 'log'),
    ('Imposto de Renda', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Imóveis Aquisição', 'DRE', 'Compra de Ativos', 'log'),
    ('Internet Telefonia e Sistemas', 'DRE', 'Despesas Administrativas', 'log'),
    ('Jardinagem', 'DRE', 'Materiais Aplicados', 'log'),
    ('Juros e Multas', 'DRE', 'Despesas Financeiras', 'log'),
    ('Juros e Multas Tributárias', 'DRE', 'Despesas Tributárias', 'log'),
    ('Juros sobre Empréstimos', 'DRE', 'Despesas Financeiras', 'log'),
    ('Locação de Equipamentos', 'DRE', 'Despesas com Terceiros', 'log'),
    ('Locação de Máquinas Pesadas', 'DRE', 'Despesas com Terceiros', 'log'),
    ('Locação de Veículos', 'DRE', 'Despesas com Terceiros', 'log'),
    ('Louças e Metais', 'DRE', 'Materiais Aplicados', 'log'),
    ('Madeiramento', 'DRE', 'Materiais Aplicados', 'log'),
    ('Manutenção Ferramentas e Equipamentos', 'DRE', 'Despesas Administrativas', 'log'),
    ('Manutenção Veículos e Máquinas', 'DRE', 'Despesas Administrativas', 'log'),
    ('Materais p/ Serralheria Tubos Metalon Perfis etc', 'DRE', 'Materiais Aplicados', 'log'),
    ('Material Elétrico', 'DRE', 'Materiais Aplicados', 'log'),
    ('Material Hidráulico e Sanitário', 'DRE', 'Materiais Aplicados', 'log'),
    ('Material de Escritório', 'DRE', 'Despesas Administrativas', 'log'),
    ('Material p/ Cabeamento Estruturado e CFTV', 'DRE', 'Materiais Aplicados', 'log'),
    ('Material p/ Climatização', 'DRE', 'Materiais Aplicados', 'log'),
    ('Material p/ Combate à Incêndio', 'DRE', 'Materiais Aplicados', 'log'),
    ('Material p/ Fôrro', 'DRE', 'Materiais Aplicados', 'log'),
    ('Material p/ Gás', 'DRE', 'Materiais Aplicados', 'log'),
    ('Material p/ Limpeza', 'DRE', 'Materiais Aplicados', 'log'),
    ('Material para Pintura', 'DRE', 'Materiais Aplicados', 'log'),
    ('Multas e Processos Trabalhistas', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Móveis e Utensílios', 'DRE', 'Materiais Aplicados', 'log'),
    ('Outras Despesas', 'DRE', 'Despesas Administrativas', 'log'),
    ('Outros Materiais', 'DRE', 'Materiais Aplicados', 'log'),
    ('PIS', 'DRE', 'Despesas Tributárias', 'log'),
    ('PIS Retido', 'DRE', 'Receitas', 'log'),
    ('Pagamento de Dividendos', 'Fluxo de Caixa', 'Saídas Financeiras', 'log'),
    ('Parafusos Ferragens e Acessórios', 'DRE', 'Materiais Aplicados', 'log'),
    ('Participação nos Lucros e Resultados', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Patrimônio Aquisição', 'DRE', 'Compra de Ativos', 'log'),
    ('Pisos Cerâmicas e Revestimentos', 'DRE', 'Materiais Aplicados', 'log'),
    ('Produção', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Pré-Moldados de Concreto', 'DRE', 'Materiais Aplicados', 'log'),
    ('RET 1%', 'DRE', 'Despesas Tributárias', 'log'),
    ('Receita de Devolução de Material', 'DRE', 'Receitas', 'log'),
    ('Receita de Obras', 'DRE', 'Receitas', 'log'),
    ('Reembolso de Custas processuais', 'DRE', 'Receitas', 'log'),
    ('Rendimentos de Aplicações', 'DRE', 'Entradas Financeiras', 'log'),
    ('Rescisões e Indenizações Trabalhistas', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Resgate de Aplicações Financeiras', 'Fluxo de Caixa', 'Entradas Financeiras', 'log'),
    ('Salários e Ordenados', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Saída de Transferência', 'TRF', 'Transferência', 'log'),
    ('Seguro de Vida', 'DRE', 'Despesas com Pessoal', 'log'),
    ('Seguros e Garantias', 'DRE', 'Despesas Financeiras', 'log'),
    ('Serviços de Terceiros Pessoa Física ou Jurídica', 'DRE', 'Despesas com Terceiros', 'log'),
    ('Solicitação de Pagamento', 'Fluxo de Caixa', 'Materiais Aplicados', 'log'),
    ('Taxas Tarifas Bancárias e IOF', 'DRE', 'Despesas Financeiras', 'log'),
    ('Telhas e Material p/ Coberturas', 'DRE', 'Materiais Aplicados', 'log'),
    ('Veículos Máquinas e Equipamentos', 'DRE', 'Venda de Ativos', 'log'),
    ('Veículos Taxas Impostos Multas', 'DRE', 'Despesas Administrativas', 'log'),
    ('Vidros e Espelhos', 'DRE', 'Materiais Aplicados', 'log'),
    ('Água e Energia', 'DRE', 'Despesas Administrativas', 'log')
ON CONFLICT (categoria) DO UPDATE
   SET analise = excluded.analise,
       grupo   = excluded.grupo,
       origem  = excluded.origem;
